administrador/urls.py
from django.contrib import admin
from django.urls import path
from alquiler import views
from django.conf import settings
from django.contrib.staticfiles.urls import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('agregar_registro', views.agregar_registro, name='agregar_registro'),
    path('registros_list', views.registro_list, name='registro_list'),
    path('get_asientos_disponibles/', views.get_asientos_disponibles, name='get_asientos_disponibles'),
    path('agregar-rol-salida/', views.agregar_rol_salida, name='agregar_rol_salida'),
    path('lista-rol-salida/', views.lista_rol_salida, name='lista_rol_salida'),
    path('cambiar_estado_rol_salida/<int:rol_id>/', views.cambiar_estado_rol_salida, name='cambiar_estado_rol_salida'),
    #logueamiento
    path('logout/', views.signout, name='logout'),
    path('signin/', views.signin, name='signin'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alquiler/models.py
#transporte que me permita vender boletos por asiento  asignarle roles de salia a 
#los vehiculos clasificar vehiculos por categoria y un registro de ganancias total  

from django.db import models
from django.conf import settings

class Categoria(models.Model):
    categoria = models.CharField(max_length=255)
    asientos = models.PositiveIntegerField()

    def __str__(self):
        return self.categoria

    class Meta:
        verbose_name_plural = "Categorías"

class Persona(models.Model):
    imagen = models.ImageField(upload_to='imagenes/usuarios', verbose_name='Imagen', null=True, blank=True)
    dni = models.CharField(verbose_name='DNI', max_length=50, unique=True, help_text='Documento Nacional de Identidad')
    fecha_nacimiento = models.DateField()
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, verbose_name='Categoría')
    telefono = models.CharField(verbose_name='Teléfono', max_length=20, blank=True, null=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, verbose_name='Usuario relacionado')
    estado = models.BooleanField(default=True)
    #turno = models.ForeignKey(Turno, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Turno')


    def __str__(self):
        return str(self.user)

    class Meta:
        verbose_name_plural = "Personas"
        ordering = ['user']
        
class Turno(models.Model):
    nombre = models.CharField(max_length=50)
    hora_inicio = models.TimeField()
    hora_fin = models.TimeField()
    def __str__(self):
        return self.nombre
    
class RolSalida(models.Model):
    STATUS_CHOICES = [
        ('pendiente', 'Pendiente'),
        ('realizado', 'Realizado'),
    ]

    nombre = models.CharField(max_length=50, verbose_name='Agregar Turno o Descripcion')
    hora_inicio = models.TimeField()
    hora_fin = models.TimeField()
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE, verbose_name='Asignar Personal o Chofer')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pendiente', verbose_name='Estado')

class ventaboletos(models.Model):
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE, verbose_name='Chofer o Persona a Cargo')
    cliente = models.CharField(max_length=150, verbose_name='Cliente')
    detalle = models.TextField(verbose_name='Detalle', blank=True, null=True)
    fecha = models.DateTimeField(auto_now_add=True)
    boleto = models.DecimalField(max_digits=10, decimal_places=2)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    asiento = models.PositiveIntegerField(verbose_name='Número de Asiento')

    def __str__(self):
        return f"{self.cliente} - Asiento {self.asiento}"

    class Meta:
        verbose_name_plural = "Registros"
        ordering = ['fecha']
        unique_together = ('persona', 'asiento')
        
        

class Registro(models.Model):
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE, verbose_name='Persona relacionada')
    cliente = models.CharField(max_length=150, verbose_name='Cliente')
    detalle = models.TextField(verbose_name='Detalle', blank=True, null=True)
    fecha = models.DateTimeField(auto_now_add=True)
    boleto = models.DecimalField(max_digits=10, decimal_places=2)
    total = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.cliente

    class Meta:
        verbose_name_plural = "Registros"
        ordering = ['fecha']

alquiler/forms.py
from django import forms
from .models import ventaboletos, Persona,RolSalida

class RolSalidaForm(forms.ModelForm):
    hora_inicio = forms.TimeField(
        widget=forms.TimeInput(format='%H:%M', attrs={'type': 'time'}),
        label='Hora de Inicio'
    )
    hora_fin = forms.TimeField(
        widget=forms.TimeInput(format='%H:%M', attrs={'type': 'time'}),
        label='Hora de Finalizacion'
    )

    class Meta:
        model = RolSalida
        fields = ['nombre', 'hora_inicio', 'hora_fin', 'persona']
        
class RegistroForm(forms.ModelForm):
    class Meta:
        model = ventaboletos
        fields = ['persona', 'cliente', 'detalle', 'boleto', 'total', 'asiento']

    def __init__(self, *args, **kwargs):
        super(RegistroForm, self).__init__(*args, **kwargs)
        if 'persona' in self.data:
            try:
                persona_id = int(self.data.get('persona'))
                persona = Persona.objects.get(id=persona_id)
                categoria = persona.categoria
                asientos_ocupados = ventaboletos.objects.filter(persona__categoria=categoria).values_list('asiento', flat=True)
                asientos_disponibles = [i for i in range(1, categoria.asientos + 1) if i not in asientos_ocupados]
                self.fields['asiento'].choices = [(i, i) for i in asientos_disponibles]
            except (ValueError, TypeError, Persona.DoesNotExist):
                pass
        else:
            self.fields['asiento'].choices = []

alquiler/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import RegistroForm
from .models import ventaboletos,Categoria

def home(request):
    return render(request, 'home.html')


    
def signout(request):
    logout(request)
    return redirect('home')

def signin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            error_message = "Usuario y/o contraseña incorrectos."
            return render(request, 'signin.html', {'error_message': error_message})
    return render(request, 'signin.html')

def agregar_registro(request):
    if request.method == 'POST':
        form = RegistroForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = RegistroForm()
    return render(request, 'agregar_registro.html', {'form': form})

from django.utils.dateparse import parse_date
from django.db.models import Sum

def registro_list(request):
    registros = ventaboletos.objects.all()
    total_ganancias = 0

    # Obtener las fechas y categoría del formulario de entrada
    fecha_inicio = request.GET.get('fecha_inicio')
    fecha_fin = request.GET.get('fecha_fin')
    categoria_id = request.GET.get('categoria')

    if fecha_inicio and fecha_fin:
        fecha_inicio = parse_date(fecha_inicio)
        fecha_fin = parse_date(fecha_fin)
        registros = registros.filter(fecha__range=[fecha_inicio, fecha_fin])

    if categoria_id:
        registros = registros.filter(persona__categoria_id=categoria_id)

    total_ganancias = registros.aggregate(Sum('total'))['total__sum'] or 0

    categorias = Categoria.objects.all()

    return render(request, 'registro_list.html', {
        'registros': registros,
        'total_ganancias': total_ganancias,
        'fecha_inicio': fecha_inicio,
        'fecha_fin': fecha_fin,
        'categoria_id': categoria_id,
        'categorias': categorias,
    })

from django.http import JsonResponse
from .models import Persona

def get_asientos_disponibles(request):
    persona_id = request.GET.get('persona_id')
    persona = Persona.objects.get(id=persona_id)
    categoria = persona.categoria
    asientos_ocupados = ventaboletos.objects.filter(persona__categoria=categoria).values_list('asiento', flat=True)
    asientos_disponibles = [i for i in range(1, categoria.asientos + 1) if i not in asientos_ocupados]
    return JsonResponse({'asientos_disponibles': asientos_disponibles, 'asientos_ocupados': list(asientos_ocupados)})


from .forms import RolSalidaForm

def agregar_rol_salida(request):
    if request.method == 'POST':
        form = RolSalidaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')  # Redirige a la lista de roles de salida después de agregar uno nuevo
    else:
        form = RolSalidaForm()
    return render(request, 'agregar_rol_salida.html', {'form': form})

# views.py
from .models import RolSalida
from datetime import datetime, date, timedelta

def lista_rol_salida(request):

    categorias = Categoria.objects.all()

   
    categoria_filtrar = request.GET.get('categoria', None)

    now = datetime.now()
    start_of_day = datetime.combine(date.today(), datetime.min.time())
    end_of_day = datetime.combine(date.today(), datetime.max.time())

    
    roles_salida = RolSalida.objects.filter(
        persona__categoria__categoria=categoria_filtrar,
        hora_inicio__gte=start_of_day.time(),
        hora_inicio__lte=end_of_day.time(),
        status='pendiente'
    )

    return render(request, 'lista_rol_salida.html', {'roles_salida': roles_salida, 'categorias': categorias})

from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse

def cambiar_estado_rol_salida(request, rol_id):
    rol = get_object_or_404(RolSalida, id=rol_id)
    if rol.status == 'pendiente':
        rol.status = 'realizado'
        rol.save()
    return HttpResponseRedirect(reverse('lista_rol_salida'))

alquiler/templates/agregar_registro.html
{% extends 'principal.html' %}
{% load crispy_forms_tags %}
{% block content %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<div class="container px-lg-5 font">
    <div class="container px-lg-5 ">
        <div class="container">
            <h1 id="letr" class="text-center titulo pb-2 pt-5">REGISTRO DE VENTA DE PASAJES </h1>
            <div class="row texto contenedor">
                <!-- Primera columna: Formulario -->
                <div class="col-md-8 pt-4">
                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}<br>
                        <a>
                            <input name="" id="boton1" class="btn btn-primary m-2" type="submit" value="Enviar Información">
                        </a>
                        <a name="" id="boton1" class="btn btn-danger m-2" href="{% url 'home' %}" role="button">Cancelar</a>
                    </form>
                    <br>
                </div>
    
                <!-- Segunda columna: Asientos disponibles y ocupados -->
                <div class="col-md-4 text-right pt-4">
                    <div class="row">
                        <div class="col-5">
                            <h6>Disponibles</h6>
                            <ul id="asientos-disponibles" class="list-group"></ul>
                        </div>
                        <div class="col-5">
                            <h6>Ocupados</h6>
                            <ul id="asientos-ocupados" class="list-group"></ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><br><br><br><br>
<script type="text/javascript">
    $(document).ready(function() {
        $('#id_persona').change(function() {
            var personaId = $(this).val();
            $.ajax({
                url: '{% url "get_asientos_disponibles" %}',
                data: {
                    'persona_id': personaId
                },
                success: function(data) {
                    var $asiento = $('#id_asiento');
                    var $asientosDisponibles = $('#asientos-disponibles');
                    var $asientosOcupados = $('#asientos-ocupados');
                    $asiento.empty();
                    $asientosDisponibles.empty();
                    $asientosOcupados.empty();
                    
                    $.each(data.asientos_disponibles, function(index, value) {
                        $asiento.append($('<option></option>').attr('value', value).text(value));
                        $asientosDisponibles.append($('<li></li>').addClass('list-group-item').text(value));
                    });
                    
                    $.each(data.asientos_ocupados, function(index, value) {
                        $asientosOcupados.append($('<li></li>').addClass('list-group-item').text(value));
                    });
                }
            });
        });
    });
</script>
{% endblock %}

alquiler/templates/agregar_rol_salida.html
{% extends 'principal.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container px-lg-5 font">
    <div class="container px-lg-5 ">
        <div class="container px-lg-5 ">
            <h1 id="letr" class="text-center titulo pb-2 pt-5">AGREGAR NUEVO ROL DE SALIDA</h1>
            <div class="contenedor texto">
                <form method="post" class="px-lg-5">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <br>
                    <a>
                        <input name="" id="boton1" class="btn btn-primary" type="submit" value="Enviar Información">
                    </a>
                    <a name="" id="boton1" class="btn btn-danger" href="{% url 'home' %}" role="button">Cancelar</a>
                    
                </form>
            </div>
        </div><br><br><br>
    </div>
</div><br><br><br>
{% endblock %}

alquiler/templates/lista_rol_salida.html
{% extends 'principal.html' %}
{% block content %}
<div class="container px-lg-5 ">
    <h1 id="letr" class="text-center titulo pb-3 pt-5 font">LISTA DE ROLES Y SALIDAS DEL DIA </h1>
    <form method="get">
        <div class="row pb-2 texto px-3">
            <div class="col-md-3 pb-2 contenedor me-2">
                <label class="font pb-1" for="categoria">Filtrar por Categoría:</label>
                <select class="form-control" id="categoria" name="categoria">
                    <option value="">Todas las categorías</option>
                    {% for categoria in categorias %}
                    <option value="{{ categoria }}">{{ categoria }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md-2 d-flex align-items-end m-2 pb-2">
                <button type="submit" class="btn btn-primary">Filtrar Datos</button>
            </div>
        </div>
    </form>
    
    <div class="contenedor">
        <table class="table">
            <thead class="">
              <tr class="">
                <th scope="col">ASIGNACION</th>
                <th scope="col">HORARIO INICIO</th>
                <th scope="col">HORARIO FINALIZACION</th>
                <th scope="col">CHOFER O ENCARGADO</th>
                <th scope="col">ACCIONES</th>
              </tr>
            </thead>
            <tbody>
                {% for rol in roles_salida %}
                <tr>
                    <td data-label="Turno">{{ rol.nombre }}</td>
                    <td data-label="Hora Turno inicio">{{ rol.hora_inicio|time:"H:i" }}</td>
                    <td data-label="Hora Turno Salida">{{ rol.hora_fin|time:"H:i" }}</td>
                    <td data-label="Chofer o Responsable">{{ rol.persona }}</td>
                    <td data-label="Acciones">
                        <form action="{% url 'cambiar_estado_rol_salida' rol.id %}" method="post">
                            {% csrf_token %}
                            <button class="btn btn-success m-1" type="submit">Realizado</button>
                        </form>
                        <a name="" id="boton1" class="btn btn-warning px-4 m-1" href="" role="button">Editar</a>
                    </td>
                </tr>
                {% empty %}
                <H4 class="font text-end pb-2 texto">No hay roles de salida para mostrar.</H4>
                {% endfor %}
            </tbody>
        </table>
    </div>  
</div><br><br><br><br>
{% endblock %}

alquiler/templates/registro_list.html
{% extends 'principal.html' %}
{% block content %}
<div class="container px-lg-5 ">
    <h1 id="letr" class="text-center pb-3 pt-4 titulo font">ARQUEO Y REPORTE DE GANANCIAS</h1>
        <form method="get" class="mb-3 contenedor">
            <div class="row texto">
                <div class="col-md-3 pb-2">
                    <div class="form-group">
                        <label class="font" for="fecha_inicio">Desde la Fecha:</label>
                        <input type="date" class="form-control" id="fecha_inicio" name="fecha_inicio" value="{{ fecha_inicio }}">
                    </div>
                </div>
                <div class="col-md-3 pb-2">
                    <div class="form-group">
                        <label  class="font" for="fecha_fin">Hasta la Fecha:</label>
                        <input type="date" class="form-control" id="fecha_fin" name="fecha_fin" value="{{ fecha_fin }}">
                    </div>
                </div>
                <div class="col-md-4 pb-2">
                    <div class="form-group">
                        <label class="font" for="categoria">Categoría:</label>
                        <select class="form-control" id="categoria" name="categoria">
                            <option value="">Todas</option>
                            {% for categoria in categorias %}
                            <option value="{{ categoria.id }}" {% if categoria.id == categoria_id %}selected{% endif %}>{{ categoria.categoria }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="col-md-2 d-flex align-items-end pb-2">
                    <button type="submit" class="btn btn-primary">Filtrar Datos</button>
                </div>
            </div>
        </form>


        <h4 class="font text-end texto">Total Ganancias : {{ total_ganancias }} Bs.</h4>
        <div class="contenedor">
            <table class="table">
                <thead class="table table-dark table-striped">
                  <tr class="">
                    <th scope="col">Foto</th>
                    <th scope="col">Chofer</th>
                    <th scope="col">Categoría</th>
                    <th scope="col">Cliente</th>
                    <th scope="col">Detalle</th>
                    <th scope="col">Fecha</th>
                    <th scope="col">Boleto</th>
                    <th scope="col">Asiento</th>
                    <th scope="col">Total</th>
                  </tr>
                </thead>
                <tbody>
                    {% for registro in registros %}
                    <tr>
                        <td data-label="Foto">
                            {% if registro.persona.imagen %}
                                <img src="{{ registro.persona.imagen.url }}" class="imgicono" alt="Imagen de {{ registro.persona.user.get_full_name }}">
                            {% endif %}
                            
                        </td>
                        <td data-label="Chofer">{{ registro.persona.user.get_full_name }}</td>
                        <td data-label="Modelo de Auto">{{ registro.persona.categoria.categoria }}</td>
                        <td data-label="Nombre Cliente">{{ registro.cliente }}</td>
                        <td data-label="Detalle">{{ registro.detalle }}</td>
                        <td data-label="Fecha">{{ registro.fecha }}</td>
                        <td data-label="Boleto">N°: {{ registro.boleto }}</td>
                        <td data-label="Asiento">N°: {{ registro.asiento }}</td>
                        <td data-label="Total Pagar">{{ registro.total }} Bs.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>  
        </div>
</div><br><br><br><br>
{% endblock %}

alquiler/templates/signin.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <title>Login</title>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <!-- Bootstrap CSS v5.2.1 -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
        />
        <link type='text/css' href= "{% static 'css\style.css' %}" rel='stylesheet' />
    </head>
    <body class="" style="background-image: url({% static 'img/login2.gif' %}); height: 100vh; background-repeat: no-repeat; background-size: cover;">
        <section id="gradient-custom" class="vh-100 gradient-custom">
            <div class="container h-100 d-flex justify-content-center align-items-center">
                <div class="row w-100 d-flex justify-content-center align-items-center">
                    <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                        <div class="card  text-white" id="bg-login" style="border-radius: 1rem;">
                            <div class="card-body p-5 text-center">
                                <div class="mb-md-5 mt-md-4 pb-5">
                                    <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
                                    <form method="post">
                                        {% csrf_token %}
                                        <div class="form-outline form-white mb-4">
                                            <input type="text" id="typeEmailX" name="username" class="form-control form-control-lg" />
                                            <label class="form-label" for="typeEmailX">Email</label>
                                        </div>
                                        <div class="form-outline form-white mb-4">
                                            <input type="password" name="password" id="typePasswordX" class="form-control form-control-lg" />
                                            <label class="form-label" for="typePasswordX">Password</label>
                                        </div>
                                        <p class="small mb-5 pb-lg-2"><a class="text-black" href="#!">Forgot password?</a></p>
                                        <button class="btn btn-outline-secondary btn-lg px-5" type="submit">Iniciar</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"
        ></script>

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
            crossorigin="anonymous"
        ></script>
    </body>
</html>